# Lily58 features
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Enable every built-in ZMK display widget
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# Device and connection settings
CONFIG_ZMK_KEYBOARD_NAME="Lily58 Yorche"
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Power saving for wireless use
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
